version: '3.8'

services:
  nestjs:
    build: .
    ports:
      - "${PORT}:8081"
    environment:
      - PORT=${PORT}
      - SALT_ROUND=${SALT_ROUND}
      - SMTP_APP_PASSWORD=${SMTP_APP_PASSWORD}
      - SMTP_APP_EMAIL=${SMTP_APP_EMAIL}
      - SMTP_APP_HOST=${SMTP_APP_HOST}
      - SMTP_APP_NAME=${SMTP_APP_NAME}
      - REDIS_URI=${REDIS_URI}
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
