version: '3.8'

services:
  nestjs:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - SALT_ROUND=${SALT_ROUND}
      - REDIS_URI=${REDIS_URI}
      - DB_URI=${DB_URI}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - SEND_GRID_API_KEY=${SEND_GRID_API_KEY}
      - SEND_GRID_FROM_EMAIL=${SEND_GRID_FROM_EMAIL}
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
